# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8839b921e0c0a5cfea81b97775aa3c38e4f4943e8d98c4444f54dce3b3e6a4fa177e93116c2097931ea9913c534e995e6728d2582df5067ef6257ed00ea20c57

test:
  secret_key_base: 370a055197cea4810f2e6cb114249ad5cacc3433db0cc5bdb24e737836feaefae0c5b754ee386446b88b35d60d3ad6a2d6991df42f1958bb50303ef3fdddce89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
